package net.imagej.ops.functionbuilder;
/*
 * Simple Interface to mark Descriptors which listen for updates of external
 * inputs (i.e. inputs which are not generated by an {@link Op}).
 * 
 * @author Christian Dietz (University of Konstanz)
 */
interface InputUpdateListener {

	void update(Object o);

	boolean listensTo(Class<?> clazz);
}